spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SaiGonByDay
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: haconghieu2003@gmail.com
    password: cjla uhwf tkik yeom
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true